// every name @minecraft/server and @minecraft/server-ui export, for the ones koper's hand written
// modules do not have yet. an addon importing a name the module lacks does not load AT ALL (es module
// link error), even when it only reads EntityInventoryComponent.componentId or never touches it.
// so: every enum complete with its real values, every class with its componentId and a method per
// api method that says loudly it is not built yet. the hand written file always wins.
//
//   cd engine/koperlib-bedrock-js/tools && npm i typescript@5 @minecraft/server@<ver> ... (see README below)
//   node gen_api.mjs <hand.js> <out.js> <index.d.ts> [<more index.d.ts>...]
//
// typings are Microsoft's, MIT licensed, only names and enum values are taken from them
import ts from "typescript";
import fs from "fs";
import path from "path";

const [hand, outFile, ...dtsFiles] = process.argv.slice(2);
const api = new Map(); // name -> {kind, members: Map(name -> "method"|"prop"), base, componentId, values: Map}
for (const f of dtsFiles) {
  const sf = ts.createSourceFile(f, fs.readFileSync(f, "utf8"), ts.ScriptTarget.Latest, true);
  for (const st of sf.statements) {
    if (ts.isVariableStatement(st)) {
      for (const d of st.declarationList.declarations) {
        if (api.has(d.name.text)) continue;
        if (d.initializer && (ts.isNumericLiteral(d.initializer) || ts.isStringLiteral(d.initializer)))
          api.set(d.name.text, { kind: "const", value: d.initializer.getText(sf) });
        // `export const uiManager: UIManager;` the one instance of a class
        else if (d.type && ts.isTypeReferenceNode(d.type)) api.set(d.name.text, { kind: "const", of: d.type.typeName.getText(sf) });
      }
      continue;
    }
    const name = st.name?.text;
    if (!name) continue;
    if (ts.isEnumDeclaration(st)) {
      const e = api.get(name) || { kind: "enum", values: new Map() };
      let next = 0;
      for (const m of st.members) {
        const k = m.name.getText(sf).replace(/^['"]|['"]$/g, "");
        let v;
        if (m.initializer) { v = m.initializer.getText(sf); if (ts.isNumericLiteral(m.initializer)) next = +v + 1; }
        else v = String(next++);
        if (!e.values.has(k)) e.values.set(k, v);
      }
      api.set(name, e);
    } else if (ts.isClassDeclaration(st)) {
      const c = api.get(name) || { kind: "class", members: new Map() };
      c.base = c.base || st.heritageClauses?.find((h) => h.token === ts.SyntaxKind.ExtendsKeyword)?.types?.[0]?.expression?.getText(sf);
      for (const m of st.members) {
        if (!m.name || m.modifiers?.some((x) => x.kind === ts.SyntaxKind.PrivateKeyword)) continue;
        const n = m.name.getText(sf);
        const isStatic = m.modifiers?.some((x) => x.kind === ts.SyntaxKind.StaticKeyword);
        if (isStatic) {
          if (n === "componentId" && m.initializer) c.componentId = m.initializer.getText(sf);
          // DimensionTypes.getAll & co. skipping these made them "not a function" instead of loud
          else if (ts.isMethodDeclaration(m)) (c.statics ||= new Set()).add(n);
          continue;
        }
        if (ts.isMethodDeclaration(m)) c.members.set(n, "method");
        else if (!c.members.has(n)) c.members.set(n, "prop");
      }
      api.set(name, c);
    }
  }
}

// what the hand written module already has, read by loading it with a pipe that answers nothing
globalThis.__koper = globalThis.__koper || { ask: () => undefined, on() {}, handlers: {}, rawToComponent: (x) => x, apiMajor: 2 };
const handSrc = fs.readFileSync(hand, "utf8");
const mod = await import("file://" + path.resolve(hand) + "?t=" + Date.now());
const has = (n) => Object.prototype.hasOwnProperty.call(mod, n);

const out = [];
out.push("// ── generated by tools/gen_api.mjs from the @minecraft typings (MIT): names + enum values only ──");
out.push("// do not edit, rerun the tool. hand written code above always wins over anything here");
const guard = (s) => JSON.stringify(s);

// enums: new ones whole, known ones get the members they miss (enumOf keeps them open until the end)
for (const [n, a] of api) {
  if (a.kind !== "enum") continue;
  const pairs = [...a.values].map(([k, v]) => `${guard(k)}: ${v}`).join(", ");
  if (!has(n)) out.push(`export const ${n} = enumOf({ ${pairs} });`);
  else if (handSrc.includes(`export const ${n} = enumOf(`)) {
    const miss = [...a.values].filter(([k]) => !(k in mod[n]));
    if (miss.length) out.push(`__koperFill(${n}, { ${miss.map(([k, v]) => `${guard(k)}: ${v}`).join(", ")} });`);
  }
}
for (const [n, a] of api) if (a.kind === "const" && !has(n) && a.value !== undefined) out.push(`export const ${n} = ${a.value};`);

// classes, bases first. a base that is neither hand written nor in the api is dropped
const done = new Set();
function emit(n) {
  const a = api.get(n);
  if (!a || a.kind !== "class" || done.has(n)) return;
  done.add(n);
  if (has(n)) {
    // hand written: only methods it misses, as loud stubs. properties are left alone, a stub getter
    // would break a class that assigns the same name in its constructor
    const proto = mod[n].prototype;
    for (const [m, kind] of a.members) {
      if (kind !== "method" || !proto) continue;
      let found = false;
      for (let p = proto; p; p = Object.getPrototypeOf(p)) if (Object.getOwnPropertyNames(p).includes(m)) found = true;
      if (!found && !new RegExp(`this\\.${m}\\s*=`).test(handSrc)) out.push(`__koperStub(${n}, ${guard(m)});`);
    }
    for (const m of a.statics || []) if (typeof mod[n][m] !== "function") out.push(`__koperStaticStub(${n}, ${guard(m)});`);
    if (a.componentId && mod[n].componentId === undefined) out.push(`${n}.componentId = ${a.componentId};`);
    return;
  }
  let base = a.base;
  if (base && base !== "Error" && !has(base)) { emit(base); if (!done.has(base) || api.get(base)?.kind !== "class") base = undefined; }
  const body = [];
  if (a.componentId) body.push(`static componentId = ${a.componentId};`);
  for (const m of a.statics || []) body.push(`static ${m}() { nope(${guard(n + "." + m)}); }`);
  for (const [m, kind] of a.members) if (kind === "method") body.push(`${guard(m).slice(1, -1).match(/^[A-Za-z_$][\w$]*$/) ? m : "[" + guard(m) + "]"}() { nope(${guard(n + "." + m)}); }`);
  out.push(`export class ${n}${base ? " extends " + base : ""} { ${body.join(" ")} }`);
}
for (const n of api.keys()) emit(n);
for (const [n, a] of api) if (a.kind === "const" && !has(n) && a.of) out.push(`export const ${n} = ${api.get(a.of)?.kind === "class" || has(a.of) ? "new " + a.of + "()" : "undefined"};`);
out.push("__koperSeal();");
fs.writeFileSync(outFile, out.join("\n") + "\n");
console.log(`${outFile}: ${out.length - 3} lines`);
