// ── generated by tools/gen_api.mjs from the @minecraft typings (MIT): names + enum values only ──
// do not edit, rerun the tool. hand written code above always wins over anything here
export const DataDrivenScreenClosedReason = enumOf({ "ClientClosed": 'ClientClosed', "ServerClosed": 'ServerClosed', "UserBusy": 'UserBusy' });
export const FormVisibilityErrorReason = enumOf({ "AlreadyShowing": 'AlreadyShowing', "NotShowing": 'NotShowing' });
export const TextFilteringError = enumOf({ "DisabledByPlayer": 'DisabledByPlayer', "TextProcessorServiceUnreachable": 'TextProcessorServiceUnreachable', "Unknown": 'Unknown' });
export class FormResponse {  }
export class ActionFormResponse extends FormResponse {  }
export class MessageFormResponse extends FormResponse {  }
export class ModalFormResponse extends FormResponse {  }
export class UIManager { closeAllForms() { nope("UIManager.closeAllForms"); } }
export class FormVisibilityError extends Error {  }
export class InvalidFormError extends Error {  }
export class InvalidFormModificationError extends Error {  }
export class InvalidObservableError extends Error {  }
export class PlayerLeftError extends Error {  }
__koperSeal();
